# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_pcov <- function(X, Y, R, term_S2) {
    .Call(`_pit_rcpp_pcov`, X, Y, R, term_S2)
}

rcpp_pht <- function(X, Y, R) {
    .Call(`_pit_rcpp_pht`, X, Y, R)
}

