---
title: "Introduction to pit INT"
author: "HaotianLuo"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to pit INT}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Overview

__pit__ is a simple R package to compare to way of testing independency by using projection correlation. Projection correlation has several appealing properties. It equals 0 if and only if the two random vectors are independent, it is not sensitive to the dimension of two random vectors, it is invariant w.r.t group of orthogonal transformations, and its estimation if free of tuning parameters and does not require moment conditions on the random vectors.  Two functions are written to implement two projection correlation methods, namely, _pit_ (using unweighted density function when calculating the statistics) and _pht_ (using weighted density function when calculating the statistics). For each function, we use cpp functions since we have to do circulations many times.

Example for univariate case of _pcov_:
```{r}
# num <- 10
#  x <- rnorm(num)
#  y <- rnorm(num)
#  pcov.test(x, y)
#  y <- x + rnorm(num)
#  pcov.test(x, y)
# 
# 
# Example for multivariate case of _pcov_:
# 
# p <- 3
# num <- 10
# x <- matrix(rnorm(num * p), nrow = num)
# y <- matrix(rnorm(num * p), nrow = num)
# pcov.test(x, y)
# y <- x + matrix(rnorm(num * p), nrow = num)
# pcov.test(x, y)
# 
# 
# Example for univariate case of _pit_:
# 
# num <- 10
# x <- rnorm(num)
# y <- rnorm(num)
# pht.test(x, y)
# y <- x + rnorm(num)
# pht.test(x, y)
# 
# 
# 
# Example for multivariate case of _pit_:
# 
# p <- 3
# x <- matrix(rnorm(num * p), nrow = num)
# y <- matrix(rnorm(num * p), nrow = num)
# pht.test(x, y)
# y <- x + matrix(rnorm(num * p), nrow = num)
# pht.test(x, y)
```


